stages:
  load_stage:
    cmd: python src/stage_01_load_and_save.py -c config/config.yaml
    deps:
      - config/config.yaml
      - src/stage_01_load_and_save.py
      - src/utils/all_utils.py
    outs:
      - artifacts/raw_local_dir/data.csv
  
  split_data:
    cmd: python src/stage_02_split_data.py -c config/config.yaml -p params.yaml
    deps:
      - artifacts/raw_local_dir/data.csv
      - src/stage_02_split_data.py
      - config/config.yaml
      - src/utils/all_utils.py
    params:
      - base.random_state
      - base.test_size
    outs:
      - artifacts/split_data/train.csv
      - artifacts/split_data/test.csv
    
