stages:
  load_stage:
    cmd: python src/stage_01_load_and_save.py -c config/config.yaml
    deps:
      - config/config.yaml
      - src/stage_01_load_and_save.py
      - src/utils/all_utils.py
    outs:
      - artifacts/raw_local_dir/data.csv
